name: Build

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js v21
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Setup API server
        run: |
          git clone https://github.com/virtual-designer/sudobot-dummy-api;
          cd sudobot-dummy-api;
          npm install;
          npm start &

      - name: Create .env
        run: echo "NEXT_PUBLIC_API_URL=http://localhost:5060" >> .env

      - name: Build
        run: npm run build

  build-bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup API server
        run: |
          git clone https://github.com/virtual-designer/sudobot-dummy-api;
          cd sudobot-dummy-api;
          npm install;
          npm start &

      - name: Create .env
        run: echo "NEXT_PUBLIC_API_URL=https://localhost:5060" >> .env

      - name: Build
        run: bun run build
