name: Releases
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: github.repository_owner == 'onesoft-sudo'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Git
        run: |
          echo "${{ secrets.COMMIT_GPG_KEY }}" > private.key
          gpg --import private.key
          rm -f private.key
          git config --global user.signingkey "6AE7B08C68169452"
          git config --global commit.gpgsign true

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "./package.json"
          git-user-name: "Conventional Changelog Action"
          git-user-email: rakinar2@onesoftnet.eu.org
          git-message: |
            release: {version} [skip ci]

            Signed-off-by: Ar Rakin <rakinar2@onesoftnet.eu.org>

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
